# Generated by Django 5.0.2 on 2024-03-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
